name: build

on: [push]
#on:
#  push:
#    tags:
#      - 'v*'
#  #if: ${{ github.ref_type == 'tag'}}

defaults:
  run:
    shell: bash

env:
  BUILD_TYPE: Release

jobs:
  create-source-archive:
    runs-on: ubuntu-20.04

    outputs:
        artifact-name: ${{ env.ARCHIVE_NAME }}

    steps:
    - name: Check out sources
      uses: actions/checkout@v3.3.0
      with:
        path: GxPlugins.lv2
        submodules: recursive

    - name: create source package
      run: tar --exclude=.git* -cjf GxPlugins.tar.bz2 GxPlugins.lv2

    - name: Set Archive Name
      run: echo "ARCHIVE_NAME=gxplugins-source-code" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: GxPlugins.tar.bz2

  build-linux:
    runs-on: ubuntu-latest

    outputs:
      artifact-name: ${{ env.ARCHIVE_NAME }}

    steps:
    - name: Check out sources
      uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: install lv2
      run: |
        sudo apt-get install lv2-dev debhelper fakeroot
    - name: build deb
      run: dpkg-buildpackage -rfakeroot -uc -us -b
    - name: copy deb
      run: cp ../gxplugins_*_amd64.deb .

    - name: Set Archive Name
      run: echo "ARCHIVE_NAME=gxplugins-linux" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: gxplugins_*_amd64.deb

  build-windows:
    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    outputs:
        artifact-name: ${{ env.ARCHIVE_NAME }}

    steps:
    - name: Prepare MSys2
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          base-devel
          git
          make
          mingw-w64-x86_64-gcc
          mingw-w64-x86_64-lv2
          mingw-w64-x86_64-cairo
          mingw-w64-x86_64-pkgconf
          pkgconf
          mingw-w64-x86_64-7zip

    - name: Check out sources
      uses: actions/checkout@v3.3.0
      with:
        submodules: recursive

    - name: make
      run: make -j && make DESTDIR=$(pwd)/_bin install
    - name: add license and readme
      run: cp LICENSE README.md _bin~/.lv2/
    - name: zip
      run: mv _bin~/.lv2 _bin~/lv2 ; cd _bin~ ; 7z a -mx9 ../plugin.7z lv2 ; cd ..

    - name: Set Archive Name
      run: echo "ARCHIVE_NAME=gxplugins-windows" >> "$GITHUB_ENV"

    - uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ env.ARCHIVE_NAME }}
        path: plugin.7z

  release:
    runs-on: ubuntu-20.04
    #if: ${{ github.ref_type == 'tag'}}

    outputs:
        tag-name: ${{ env.TAG_NAME }}

    needs:
      - create-source-archive
      - build-linux
      - build-windows

    steps:
    # move tag: delete old
    - name: Delete tag 'Latest'
      #uses: dev-drprasad/delete-tag-and-release@v0.2.0
      uses: dev-drprasad/delete-tag-and-release@master
      with:
        delete_release: false
        tag_name: Latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # move tag: create new
    - name: Add tag 'Latest'
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "Latest"

    - name: Download all artifacts
      uses: actions/download-artifact@v3.0.2

    - name: Create Archives
      run: |
        TAG_NAME=${{ github.ref_TAG_NAME }} # branch or tag
        if [[ ${{ github.ref_type }} == 'tag' ]] \
        && [[ $TAG_NAME =~ ^v[0-9] ]] ; then
          TAG_NAME=${TAG_NAME:1} # remove leading 'v' from tag (v1.0 -> 1.0)
        elif [[ $TAG_NAME == onpush ]] ; then
          TAG_NAME=Latest
        fi
        echo "TAG_NAME=$TAG_NAME" >> "$GITHUB_ENV"
        mv gxplugins-source-code/GxPlugins.tar.bz2 ./gxplugins_${TAG_NAME}_src.tar.bz2
        mv gxplugins-linux/gxplugins_*_amd64.deb   ./gxplugins_${TAG_NAME}_amd64.deb
        mv gxplugins-windows/plugin.7z             ./gxplugins_${TAG_NAME}_win64.7z

    - uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ env.TAG_NAME }}
        prerelease: true
        files: |
          *_src.tar.bz2
          *_amd64.deb
          *_win64.7z
